version: "3"

services:

  nginx:
    build:
      context: ./docker/dev/nginx
    env_file: env
    ports:
      - "80:80"
    links:
      - php
    volumes:
      - .:/www
#      - ./mylogo.png:/www/web/static/logo.png # If you want to load your own logo

  php:
    build:
      context: ./docker/dev/php
    env_file: env
    links:
      - database
    volumes:
      - .:/www

  database:
    image: postgres:10.3-alpine
    volumes:
      - db:/var/lib/postgresql/data
    env_file: env

  adminer:
   image: adminer
   links:
     - database
   ports:
     - 8080:8080

volumes:
  db: ~
